### PR TITLE
Added Fabric

### PR DESCRIPTION
**Pull request by brunodlz**
I use and recommend it.

### CODE REVIEW

**Comment by kiliankoe** [comment]
It is pretty much the same as Crashlytics right below though, isn't it? Since Fabric offers a bit more than just Crashlytics though one might as well just remove Crashlytics from the list in favor of Fabric :)

**Comment by brunov0id** [comment]
Yes, you're right. Today, within the Crashlytics page he recommends Fabric.

**Comment by brunodlz** [comment]
I removed Crashlytics.

**Comment by richeterre** [comment]
Thanks, will merge!

**Pull request merged**
