### PR TITLE
Update: Best practice for Pods added in Note.

### PR DESCRIPTION
**Pull request by siddharthsuneel**

### CODE REVIEW

**Comment by siddharthsuneel** [comment]
@richeterre  @ali-rantakari  can we merge this PR ?

**Comment by mkko** [comment]
I would say this is a bit controversial topic. Even though I'm submitting the pods into repo I would not officially recommend this as there are cons as well. Instead of recommendation, we could note this in the guide with an extensive list of pros and cons. What do you guys think? @erwald, @Sebastian-Hojas, whoever else's active here?

**Comment by mkko** [comment]
@siddharthsuneel, I would recommend changing this as an alternative, not a best practice. Most of the time it is good to check in the pods too, but it has its shortcomings. I think it'd be valuable to know why it is an alternative and what are the effects of checking the pods in.

**Comment by erwald** [comment]
Hm, actually I would consider this a best practice in the majority of cases, and besides, it's the recommended way of doing it [by CocoaPods themselves](https://guides.cocoapods.org/using/using-cocoapods.html): "We recommend that you keep the Pods directory under source control, and don't add it to your .gitignore."

But I think the wording here can be improved, and we can maybe mention that there are some advantages of not doing so. Do you mind if I write a revised version of your text, @siddharthsuneel ?

Oh and sorry for the slow responses here. We need to take better care of this repository!

**Comment by mkko** [comment]
Oh, they've changed it at some point. I do agree that it's a good thing to do though, it just adds a lot of noise to git diffs and is a good source for merge conflicts. I would suggest bringing up both, pros and cons with this one.

**Comment by erwald** [comment]
Right, I'll make a draft this weekend and we'll see what you and @siddharthsuneel think about it.

**Comment by erwald** [comment]
On second thought, I will reject this, because we already address the subject a few lines further up:

> It is generally recommended to commit the installed dependencies to your own repo, instead of relying on having each developer running `pod install` after a fresh checkout.

I will, however, create a separate PR noting that it is also the CocoaPods-endorsed way of doing it.

**Pull request closed without merging**
