### PR TITLE
Modernizations, especially regarding Swift

### PR DESCRIPTION
**Pull request by richeterre**

### CODE REVIEW

**Comment by phadej** [comment]
I'm a bit :-1: for purging Obj-c code examples. Obj-C and swift ones could live side-by-side (or one under another) for some time. Not everyone is jumped into swift train yet.

**Comment by phadej** [comment]
Also don't like security list rewrite. New section is TL;DR.

**Comment by richeterre** [comment]
But did the code examples really become more difficult to read in the process? Mostly what matters in them is the method name (`requiresConstraintBasedLayout`, `viewDidLoad` etc.) which is exactly the same in Swift.

**Comment by phadej** [comment]
I'd still stick with Obj-C for now. People fluent with Swift are fluent with Obj-C too. Not vice versa.

**Comment by richeterre** [comment]
Have you been to any iOS developer conference lately? People _apologized_ on stage for showing Obj-C code. We got contacted by people asking about Swift updates already around the time this very document was first launched.

**Comment by phadej** [comment]
Then I'd move all Obj-C stuff into *Objective-C section*. Seems there are only mentions about constants and style guides (didn't checked, whether they talk about swift too).

Also one probably have to add mention that Faux Pas doesn't lint swift code (AFAIK), but is still useful (as there is other stuff to check).

**Comment by richeterre** [comment]
@phadej, I re-added most of the code examples in Objective-C, so we now have both worlds represented :smiley: Also clarified Faux Pas' Swift support and a lot of other things based on feedback by @erikjalevik.

**Pull request merged**
